src/Entity/Departement.php
<?php

namespace App\Entity;

use App\Repository\DepartementRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DepartementRepository")
 */
class Departement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups ("Departments")
     */
    private $id;

/**
* @ORM\Column(type="string", length=255)
* @Assert\Length(
* min = 5,
* max = 30,
* minMessage = "Le nom d'un departement doit comporter au moins {{ limit }} caractères",
* maxMessage = "Le nom d'un departement doit comporter au plus {{ limit }} caractères"
* )
 * @Groups ("Departments")
 *  @Groups ("Reunions")
*/
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * * @Assert\Length(
     * min = 5,
     * max = 30,
     * minMessage = "Le nom du chef de departement doit comporter au moins {{ limit }} caractères",
     * maxMessage = "Le nom du chef de departement doit comporter au plus {{ limit }} caractères"
     * )
     * @Groups ("Departments")
     */
    private $chef_dep;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reunion", mappedBy="departement")
     * @Groups ("Departments")
     */
    private $reunions;
    public function __construct()
    {
        $this->reunions = new ArrayCollection();
        $this->users = new  ArrayCollection();
    }


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="departement")
     * @Groups ("Departments")
     */
    private $users;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getChefDep(): ?string
    {
        return $this->chef_dep;
    }

    public function setChefDep(?string $chef_dep): self
    {
        $this->chef_dep = $chef_dep;

        return $this;
    }
    /**
     * @return Collection|Reunion[]
     */
    public function getReunions(): Collection
    {
        return $this->reunions;
    }
    public function addReunion(Reunion $reunion): self
    {
        if (!$this->reunions->contains($reunion)) {
            $this->reunions[] = $reunion;
            $reunion->setDepartement($this);
        }
        return $this;
    }
    public function removeReunion(Reunion $reunion): self
    {
        if ($this->reunions->contains($reunion)) {
            $this->reunions->removeElement($reunion);
            // set the owning side to null (unless already changed)
            if ($reunion->getDepartement() === $this) {
                $reunion->setDepartement(null);
            }
        }
        return $this;
    }
    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }
    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setDepartement($this);
        }
        return $this;
    }
    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getDepartement() === $this) {
                $user->setDepartement(null);
            }
        }
        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;
use Symfony\Component\Serializer\Annotation\Groups;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("note")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Groups("np")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     * @Groups("np")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\Length(
     * min = 8,
     * max = 20,
     * minMessage = "Le mot de passe doit comporter au moins {{ limit }} caractères",
     * maxMessage = "Le mot de pass doit comporter au plus {{ limit }} caractères"
     * )
     */
    private $Mdp;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $role;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Assiduite", mappedBy="user")
     */
    private $Assiduites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Cour", mappedBy="classe")
     */
    private $cours;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DemConvention", mappedBy="id_user_id")
     */
    private $demconvs;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="user")
     */
    private $events;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Reunion", mappedBy="users")
     */
    private $reunions;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Departement", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $departement;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="user")
     */
    private $notes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }
    public function __construct()
    {
        $this->Assuduites = new ArrayCollection();
        $this->events=new ArrayCollection();
        $this->cours=new ArrayCollection();
        $this->demconvs=new ArrayCollection();
        $this->notes=new ArrayCollection();
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->Mdp;
    }

    public function setMdp(string $Mdp): self
    {
        $this->Mdp = $Mdp;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTime
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTime $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }
    /**
     * @return Collection|Assiduite[]
     */
    public function getAssiduite(): Collection
    {
        return $this->Assiduites;
    }
    public function addAssiduite(Assiduite $assiduite): self
    {
        if (!$this->Assiduites->contains($assiduite)) {
            $this->Assuduites[] = $assiduite;
            $assiduite->setUser($this);
        }
        return $this;
    }
    public function removeAssiduite(Assiduite $assiduite): self
    {
        if ($this->Assiduites->contains($assiduite)) {
            $this->Assuduites->removeElement($assiduite);
            // set the owning side to null (unless already changed)
            if ($assiduite->getUser() === $this)
            {
                $assiduite->setUser(null);
            }
        }
        return $this;
    }/**
     * @return Collection|Evenement[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }
        public function addEvent(Evenement $evenement): self
    {
        if (!$this->events->contains($evenement)) {
            $this->events[] = $evenement;
            $evenement->setUser($this);
        }
        return $this;
    }
    public function removeEvent(Evenement $evenement): self
    {
        if ($this->events->contains($evenement)) {
            $this->events->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getUser() === $this)
            {
                $evenement->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return  Collection|DemConvention[]
     */
    public function getDemconvs()
    {
        return $this->demconvs;
    }
    public function addDemconv(DemConvention $demConvention): self
    {
        if (!$this->demconvs->contains($demConvention)) {
            $this->demconvs[] = $demConvention;
        }
        return $this;
    }
    public function removeDemconv(DemConvention $demConvention): self
    {
        if ($this->demconvs->contains($demConvention)) {
            $this->demconvs->removeElement($demConvention);
        }
        return $this;
    }
    /**
     * @return Collection|Cour[]
     */
    public function getCours(): Collection
    {
        return $this->cours;
    }
    public function addCour(Cour $cour): self
    {
        if (!$this->cours->contains($cour)) {
            $this->cours[] = $cour;
            $cour->setUser($this);
        }
        return $this;
    }
    public function removeCour(Cour $cour): self
    {
        if ($this->cours->contains($cour)) {
            $this->cours->removeElement($cour);
            // set the owning side to null (unless already changed)
            if ($cour->getUser() === $this) {
                $cour->setUser(null);
            }
        }
        return $this;
    }
    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }
    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }
        return $this;
    }
    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }
    }

    /**
     * @return Collection|Reunion[]
     */
    public function getReunions(): Collection
    {
        return $this->reunions;
    }
    public function addReunion(Reunion $reunion): self
    {
        if (!$this->reunions->contains($reunion)) {
            $this->reunions[] = $reunion;
            $reunion->addUser($this);
        }
        return $this;
    }
    public function removeReunion(Reunion $reunion): self
    {
        if ($this->reunions->contains($reunion)) {
            $this->reunions->removeElement($reunion);
            $reunion->removeUser($this);
        }
        return $this;
    }

    public function getDepartement(): ?Departement
    {
        return $this->departement;
    }
    public function setDepartement(?Departement $departement): self
    {
        $this->departement = $departement;
        return $this;
    }

    public function getPrenomNom(): ?string
    {
        return $this->nom." ".$this->prenom;
    }

}

src/Form/DepartementType.php
<?php

namespace App\Form;

use App\Entity\Departement;
use App\Entity\Enseignant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DepartementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('chef_dep')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Departement::class,
        ]);
    }
}

templates/departement/aa.html.twig
{% extends 'base1.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block stylesheets %}
    <style>
        #calendrier{
            width: 80%;
            margin: auto;
        }
    </style>
{% endblock %}

{% block body %}
    <div id="calendrier">
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {
            let calendarElt = document.querySelector("#calendrier")
            let calendar = new FullCalendar.Calendar(calendarElt, {
                initialView: 'dayGridMonth',

            })
            calendar.render()
        }
    </script>

{% endblock %}

templates/departement/affectEns.html.twig
{% extends 'base1.html.twig' %}
{% block title %}

 {% endblock %}
{% block body %}

<div style="padding-left: 400px ;color: darkred"> Liste Des Enseignants</div>
    <table style="margin: auto ;padding-top: 100px" class="table table-striped">

        {% if enseignants %}
        <tbody>

        {% for ens in enseignants %}
            <tr>
                <td>
                    {{ ens.username }}
                </td>
                 <td> <a href="/affectEns/{{ ens.id }}/{{ idR }}" class="btn" style="background-color: darkgray;border-color: darkred"
                        onclick="return confirm('Etes vous sûr daffecter cet Enseignant ?');">Affecter</a></td>


            </tr>
        {% endfor %}

        </tbody>
        {% else %}
            <p>Aucun enseignant à affecter</p>
        {% endif %}
    </table>


{% endblock %}

templates/departement/edit.html.twig
{% extends 'base1.html.twig' %}
{% block title %}Modifier Departement{% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Modifier</button>
    {{ form_end(form) }}
{% endblock %}

templates/departement/editReu.html.twig
{% extends 'base1.html.twig' %}
{% block title %}Modifier Reunion{% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Modifier</button>
    {{ form_end(form) }}
{% endblock %}

templates/departement/index.html.twig
{% extends 'base1.html.twig' %}
{% block title%} Liste des Departements{% endblock %}
{% block body %}

<h1 style="margin-top: 50px ; margin-bottom: 50px;
padding-left: 370px ; color: #8b0000"> Liste des Departements </h1>

{{ form_start(form) }}
<div class="form-row align-items-end" >
    <div class="col">
        {{ form_row(form.nom) }}
    </div>
    <div class="col">
        <div class="form-group">
            <button type="submit" style="background-color: darkgray;border-color: darkred" class="btn btn-success">Rechercher</button>
            <a href="{{ path('new_departement') }}" style="background-color: darkgray;border-color: darkred" class="btn btn-success">Ajouter Departement</a>
        </div>

    </div>

</div>
{{ form_end(form) }}
{% if departements %}
<table id="departements" class="table table-striped">
    <thead>
    <tr>
        <th>Nom</th>
        <th>Chef_Dep</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for departement in departements %}
        <tr>
            <td>{{ departement.nom }}</td>
            <td>{{ departement.chefdep }}</td>
            <td>
                <a href="/departement/{{ departement.id }}" class="btn" style="background-color: darkgray;border-color: darkred" >Liste des enseignants</a>
                <a href="/departement/edit/{{ departement.id }}" class="btn btn-dark">Modifier</a>
                <a href="/departement/delete/{{ departement.id }}" class="btn btn-danger"
                   onclick="return confirm('Etesvous sûr de supprimer ce departement?');">Supprimer</a>

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <p>Aucun departement</p>
{% endif %}


{% endblock %}

templates/departement/liste.html.twig
{% extends 'base1.html.twig' %}
{% block title %}
    {{ reunion.nom }}
{% endblock %}
{% block body %}


    <table  class="table table-striped">
        <thead>
        <tr>
            <th style="padding-left: 400px ;color: darkred">  Liste des Enseignants   </th>


        </tr>

        </thead>
        <tbody >
{% for ense in departement.users  %}
        <tr>

           <td> <span class="badge badge-light">
                   {{ ense.userName }}
               </span></td>
        </tr>

{% endfor %}

        </tbody>
    </table>
    <a href="/departement" class="btn btn-success">Retour</a>
{% endblock %}

templates/departement/listeREu.html.twig
{% extends 'frontOffice.html.twig' %}


{% block body %}


    {% if reunions %}
    <table id="reunions" class="table table-striped">
    <thead>
    <tr>
        <th>Nom</th>
        <th>objectif</th>
        <th>Matiere</th>
        <th>Actions</th>

    </tr>
    </thead>
    <tbody>
    {% for reunion in reunions %}
<tr>
    <td>{{ reunion.nom }}</td>
    <td>{{ reunion.objectif }}</td>
    <td>{{ reunion.matiere }}</td>
    <td>
        <a href="/reunion/{{ reunion.id }}" class="btn btn-dark">Détails</a>
    </td>
</tr>
    </tbody>
    </table>
    {% endfor %}
    {% endif %}
    <div id="calendar"> </div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('fullCalendar/main.js') }}"></script>
    <script>

        document.addEventListener('DOMContentLoaded', function() {
            let calendarEl = document.getElementById('calendar');
            let calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridWeek',
                locale: 'fr',
                timeZone: 'Europe/Paris',
                headerToolbar: {
                    start: 'prev,next today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek'
                },
                events: {{ data | raw}},
                nowIndicator:true
            })
            calendar.on('eventChange', (e) => {
                let url = `/api/${e.event.id}/edit`
                let donnees = {
                    "title": e.event.title,
                    "description": e.event.extendedProps.description,
                    "start": e.event.start,
                    "end": e.event.end,
                    "backgroundColor": e.event.backgroundColor,
                    "borderColor": e.event.borderColor,
                    "textColor": e.event.textColor,
                    "allDay": e.event.allDay
                }

                let xhr = new XMLHttpRequest
                xhr.open("PUT", url)
                xhr.send(JSON.stringify(donnees))
            })
            calendar.render();
        });
    </script>

{% endblock %}

templates/departement/new.html.twig
{% extends 'base1.html.twig' %}
{% block title %}Ajouter Departement{% endblock %}
{% block body %}
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Créer</button>
    {{ form_end(form) }}
{% endblock %}

templates/departement/newReu.html.twig
{% extends 'base1.html.twig' %}
{% block title %}Ajouter Reunion{% endblock %}
{% block body %}
    {{ form_start(form , {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-success">Créer</button>
    {{ form_end(form) }}
{% endblock %}

templates/departement/reunion.html.twig
{% extends 'base1.html.twig' %}
{% block title%} Liste des Reunions{% endblock %}

{% block body %}
    <h1 style="margin-top: 50px ; margin-bottom: 50px;
    padding-left: 370px ; color: darkred"> Liste des Reunions </h1>
{{ form_start(form) }}
<div class="form-row align-items-end" >

    <div class="col">
        {{ form_row(form.departement) }}
    </div>
    <div class="col">
        {{ form_row(form.nom) }}
    </div>

    <div class="col">
        <div class="form-group">
            <button type="submit" style="background-color: darkgray;border-color: darkred" class="btn btn-success">Rechercher</button>
            <a href="{{ path('new_reunion') }}" style="background-color: darkgray;border-color: darkred"  class="btn btn-success">Ajouter Reunion</a>
        </div>
    </div>
</div>
{{ form_end(form) }}

    {% if reunions %}
        <table id="reunions" class="table table-striped">
            <thead>
            <tr>
                <th>Nom</th>
                <th>objectif</th>
                <th>Matiere</th>
                <th>Actions</th>

            </tr>
            </thead>
            <tbody>
            {% for reunion in reunions %}
                <tr>
                    <td>{{ reunion.nom }}</td>
                    <td>{{ reunion.objectif }}</td>
                    <td>{{ reunion.matiere }}</td>

                    <td>
                        <a href="/reunion/{{ reunion.id }}" class="btn btn-dark">Détails</a>
                        <a href="/reunion/edit/{{ reunion.id }}" class="btn btn-dark">Modifier</a>
                        <a href="/EnsToAffect/{{ reunion.id }}" class="btn btn-dark">Affect Enseignant</a>
                        <a href="/reunion/delete/{{ reunion.id }}" class="btn btn-danger"
                           onclick="return confirm('Etes vous sûr de supprimer cette reunion?');">Supprimer</a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucune reunion</p>
    {% endif %}

    <div id="calendar"> </div>

{% endblock %}
{% block javascripts %}
    <script src="{{ asset('fullCalendar/main.js') }}"></script>
    <script>

        document.addEventListener('DOMContentLoaded', function() {
            let calendarEl = document.getElementById('calendar');
            let calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridWeek',
                locale: 'fr',
                timeZone: 'Europe/Paris',
                headerToolbar: {
                    start: 'prev,next today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek'
                },
                events: {{ data | raw}},
                nowIndicator:true
            })
            calendar.on('eventChange', (e) => {
                let url = `/api/${e.event.id}/edit`
                let donnees = {
                    "title": e.event.title,
                    "description": e.event.extendedProps.description,
                    "start": e.event.start,
                    "end": e.event.end,
                    "backgroundColor": e.event.backgroundColor,
                    "borderColor": e.event.borderColor,
                    "textColor": e.event.textColor,
                    "allDay": e.event.allDay
                }

                let xhr = new XMLHttpRequest
                xhr.open("PUT", url)
                xhr.send(JSON.stringify(donnees))
            })
            calendar.render();
        });
    </script>

{% endblock %}

templates/departement/show.html.twig
{% extends 'base1.html.twig' %}
{% block title %}
{{ reunion.nom }}
{% endblock %}
{% block body %}


    <table class="table table-striped">
        <thead>
        <tr>
            <th style="color: darkred">  Reunion  {{ reunion.nom }}</th>
            <th style="color: darkred"> Donnés </th>

        </tr>

        </thead>
        <tbody>

        <tr>
            <td> Date </td>
            <td> {{reunion.start.format('d/m/Y')}}</td>
        </tr>

        <tr>
            <td>Departement </td>
            <td> {{ reunion.departement.nom }}</td>




        </tbody>
    </table >

    <table style="margin: auto ;padding-top: 100px" class="table table-striped">
        <thead>
        <tr>

            <th style="padding-left: 400px ;color: darkred"> Liste Des Enseignants </th>

        </tr>


        </thead>
        <tbody>
        {% for ens in reunion.users %}
        <tr>
            <td>
                {{ ens.username }}
            </td>
            <td> <a href="/suppens/{{ ens.id }}/{{ reunion.id }}" class="btn" style="background-color: darkgray;border-color: darkred"
                    onclick="return confirm('Etes vous sûr de supprimer cet Enseignant?');">Supprimer</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}